# Generated by Django 5.0.6 on 2024-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA9caadfbb-847d-42a3-ORDER', max_length=30, unique=True),
        ),
    ]
