# Generated by Django 5.0.6 on 2024-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_order_arrival_date_alter_order_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processed'), (2, 'Dispatch'), (3, 'En Route '), (4, 'Delivered'), (5, 'On Hold'), (6, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA36f9bc6f-5d8a-4b6e-ORDER', max_length=30, unique=True),
        ),
    ]
